apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://a26ca93af4d5241fb8e7b3c7e5f21e6c-2096177296.eu-west-1.elb.amazonaws.com/api"
  NEXTAUTH_URL: "http://a26ca93af4d5241fb8e7b3c7e5f21e6c-2096177296.eu-west-1.elb.amazonaws.com/"
  NEXTAUTH_SECRET: "HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw="
  JWT_SECRET: "e5e425764a34a2117ec2028bd53d6f1388e7b90aeae9fa7735f2469ea3a6cc8c"
